const PRIMARY_COLOR = '#190029';
const GREEN_COLOR = '#95E52E';
const SLICE_COLOR = '#38005C';
const SLICE_LIGHT_COLOR = '#5A4492';

export {PRIMARY_COLOR, GREEN_COLOR, SLICE_COLOR, SLICE_LIGHT_COLOR};
